# Site settings
title: "Matthias Matthies - Resume"
description: "Professional resume of Matthias Matthies - Computer Science graduate and Software Developer."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Matthias Matthies"
resume_title:                   "Software Developer & Computer Science Graduate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "matthias.matthies1098@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "# Add phone number"
resume_contact_address:         "Hamburg, Germany"

resume_header_contact_info:     "Hamburg, Germany • matthias.matthies1098@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Computer Science graduate with a Bachelor's degree from University of Bremen (final grade 1.56). Currently pursuing a dual Master's program at FH Wedel while working as a Masters Student at Lufthansa Technik. Experienced software developer with over 6 years of professional experience in web and backend development. Active volunteer firefighter with Freiwillige Feuerwehr Tiste since 2016.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/matthias-matthies"
  # resume_twitter_url:           "http://twitter.com/username"
  # resume_dribbble_url:          "https://dribbble.com/username"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/matthias-matthies"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://matthias-matthies.com"
  # resume_medium_url:            "https://medium.com/@username"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts